services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [ 'setFramework', [ '@contao.framework' ] ]

        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - [ 'setContainer', [ '@service_container' ] ]

    person.migration.migrate_contact_information:
        class: Cgoit\PersonsBundle\Migration\CopyContactInformationMigration
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration }

    person.migration.migrate_default_selection_mode:
        class: Cgoit\PersonsBundle\Migration\SetDefaultSelectionMode
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration }

    person.migration.migrate_size_attribute_in_modules:
        class: Cgoit\PersonsBundle\Migration\MigrateSizeAttributeInModules
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration }

