services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $personTagsManager: '@codefog_tags.manager.person_tags'
            $translator: '@contao.translation.translator'
            $arrContactInfoTypes: '%cgoit_persons.contact_types%'

    _instanceof:
        Cgoit\PersonsBundle\Controller\StudioAwareInterface:
            calls:
                - [ 'setStudio', [ '@contao.image.studio' ] ]

        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [ 'setFramework', [ '@contao.framework' ] ]

        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - [ 'setContainer', [ '@service_container' ] ]

    Cgoit\PersonsBundle\:
        resource: ../src/*

    Cgoit\PersonsBundle\Controller\ContentElement\PersonElement:
        calls:
            - [ 'setPersonTagsManager', [ '@codefog_tags.manager.person_tags' ] ]

    Cgoit\PersonsBundle\Controller\Module\PersonModule:
        calls:
            - [ 'setPersonTagsManager', [ '@codefog_tags.manager.person_tags' ] ]

    Cgoit\PersonsBundle\Helper\ContactInfoTypeHelper:
        public: true

    person.migration.migrate_contact_information:
        class: Cgoit\PersonsBundle\Migration\CopyContactInformationMigration
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration }

    person.migration.migrate_default_selection_mode:
        class: Cgoit\PersonsBundle\Migration\SetDefaultSelectionMode
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration }

    person.migration.migrate_size_attribute_in_modules:
        class: Cgoit\PersonsBundle\Migration\MigrateSizeAttributeInModules
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration }

