services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $personTagsManager: '@codefog_tags.manager.person_tags'
            $translator: '@contao.translation.translator'
            $arrContactInfoTypes: '%cgoit_persons.contact_types%'

    _instanceof:
        Cgoit\PersonsBundle\Controller\StudioAwareInterface:
            calls:
                - [ 'setStudio', [ '@contao.image.studio' ] ]

        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [ 'setFramework', [ '@contao.framework' ] ]

        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - [ 'setContainer', [ '@service_container' ] ]

        Contao\CoreBundle\Migration\AbstractMigration:
            tags: [ 'contao.migration' ]

    Cgoit\PersonsBundle\:
        resource: ../src/*

    Cgoit\PersonsBundle\Controller\ContentElement\PersonsElement:
        calls:
            - [ 'setPersonTagsManager', [ '@codefog_tags.manager.person_tags' ] ]

    Cgoit\PersonsBundle\Controller\Module\PersonsModule:
        calls:
            - [ 'setPersonTagsManager', [ '@codefog_tags.manager.person_tags' ] ]
